### ISSUE TITLE
Lantiq WAVE 300 Driver

### ISSUE THREAD

**Issue by ahmar20** [paldier/K3C#11]
Hi, I am looking for the source of Lantiq WAVE300 Drivers that you have in your build system of K3C. Where did you get the source from? How do you compile them and how do you integrate them into Openwrt? We as a community are working to support Lantiq XWAY WAVE300 wifi chip. 

You can more info here: https://forum.openwrt.org/t/support-for-wave-300-wi-fi-chip/24690

Thanks

**Comment by paldier** [comment]
my repo only support for grx500+wave500
