### ISSUE TITLE
你好想请教一下，编译源码的时候报错（看起来是找不到 u-boot-*），这种有没有什么解决方式？

### ISSUE THREAD

**Issue by mdzz0** [paldier/K3C#14]
部署环境： Ubuntu 16 64位 （已经有开启代理）
已安装软件库： (因为不清楚具体需要哪些依赖，所以把找到的openwrt编译的依赖全给装了)
>sudo apt-get -y install git gcc g++ binutils patch bzip2 make gettext pkg-config zip unzip zlib1g-dev libelf-dev autoconf libssl-dev python2.7 gawk libncurses5-dev subversion automake

>sudo apt-get -y install build-essential asciidoc python3.5 lib32gcc1 libc6-dev-i386 flex uglifyjs git-core gcc-multilib p7zip p7zip-full msmtp texinfo libglib2.0-dev xmlto qemu-utils upx libtool autopoint device-tree-compiler g++-multilib antlr3 gperf

这个实在是没搜到相关的内容，估计是我关键字不对，换了很多搜索关键字也没搜到（恩山里面搜到个类似的，但是没有回答） ，只能来发issue了；

如果方便的话看看能不能给个思路、教程或者链接什么的都可以，谢谢；

》》》》》》》》》》》》》》详细说明及错误日志《《《《《《《《《《《《《《
主要是这个文件没找到是从哪下载还是怎么的；搜索系统里面的文件时，可以找到挺多的文件，但是报错的那个位置确实没有对应的文件；
/home/ubuntu/K3C/build_dir/host/u-boot-2014.10
/home/ubuntu/K3C/dl/u-boot-2014.10.tar.bz2
/home/ubuntu/K3C/dl/u-boot-2010.06.tar.bz2

报错日志如下：（看看是否还需其他信息）
----------------------------------------------------------------------------------
/home/ubuntu/K3C/build_dir/target-mips_mips32_uClibc-0.9.33.2_grx350_1600_opensrc_71_sample/linux-lantiq_xrx500/u-boot-*/tools/mkimage -A MIPS -O Linux -C lzma -T filesystem -e 0x00 -a 0x00 -n "LTQCPE RootFS"  -d /home/ubuntu/K3C/build_dir/target-mips_mips32_uClibc-0.9.33.2_grx350_1600_opensrc_71_sample/linux-lantiq_xrx500/root.squashfs.padded /home/ubuntu/K3C/build_dir/target-mips_mips32_uClibc-0.9.33.2_grx350_1600_opensrc_71_sample/linux-lantiq_xrx500/rootfs.img.padded
bash: /home/ubuntu/K3C/build_dir/target-mips_mips32_uClibc-0.9.33.2_grx350_1600_opensrc_71_sample/linux-lantiq_xrx500/u-boot-*/tools/mkimage: No such file or directory
Makefile.openwrt:483: recipe for target 'install' failed
make[5]: *** [install] Error 127
make[5]: Leaving directory '/home/ubuntu/K3C/ugw/target/linux/lantiq/image'
Makefile:25: recipe for target 'install' failed
make[4]: *** [install] Error 2
make[4]: Leaving directory '/home/ubuntu/K3C/ugw/target/linux/lantiq'
Makefile:13: recipe for target 'install' failed
make[3]: *** [install] Error 2
make[3]: Leaving directory '/home/ubuntu/K3C/target/linux'
target/Makefile:25: recipe for target 'target/linux/install' failed
make[2]: *** [target/linux/install] Error 2
make[2]: Leaving directory '/home/ubuntu/K3C'
target/Makefile:21: recipe for target '/home/ubuntu/K3C/staging_dir/target-mips_mips32_uClibc-0.9.33.2_grx350_1600_opensrc_71_sample/stamp/.target_install' failed
make[1]: *** [/home/ubuntu/K3C/staging_dir/target-mips_mips32_uClibc-0.9.33.2_grx350_1600_opensrc_71_sample/stamp/.target_install] Error 2
make[1]: Leaving directory '/home/ubuntu/K3C'
/home/ubuntu/K3C/include/toplevel.mk:185: recipe for target 'world' failed
make: *** [world] Error 2

**Comment by paldier** [comment]
不懂就不要乱改

**Comment by mdzz0** [comment]
> 不懂就不要乱改

好吧，打扰了，，，这个还没改过东西，刚下来的源码，我再研究研究；
