### ISSUE TITLE
编译h3c

### ISSUE THREAD

**Issue by FayeSpica** [paldier/K3C#3]
在用opcc测试版
我们校园网用的是h3c(https://github.com/mcdona1d/c3h-client)    
1、想联网需要在k3c重新编译。我想知道编译是否可行，能否给一些建议
2、需要更改k3c的wifi名称与密码、5GWiFi的信道，想知道配置文件在哪。我看到了一些配置文件，但是修改还有很多问题，不确定是哪一个

**Comment by paldier** [comment]
可以试试编译，我不知道是不是行
wifi的问题暂时无解，现在启动wifi的方式是用的华硕的方法而不是sdk的方法，还在摸索中，所以现在只能以默认配置来运行
你也可以先试试修改配置的命令fapi_wlan_cli

**Comment by FayeSpica** [comment]
交叉编译ok了，已经能正常使用，谢啦！
