### ISSUE TITLE
English tutorial?

### ISSUE THREAD

**Issue by ytzone** [paldier/K3C#4]
Hello,

Would it be possible for you to create an English tutorial or video on how to install this?  I would love to install this on my K3C router, but I don't know where to start.

Thanks.

**Comment by paldier** [comment]
first, this is a test version
second, you need ssh/ttl/telnet

>     /usr/sbin/upgrade /tmp/rootfs.img rootfs 0 1
>     /usr/sbin/upgrade /tmp/uImage kernel 1 1
>     rm -rf /overlay/*
>     sync
>     reboot

default ip 192.168.1.1 or http://router.k3c.net
root admin
wifi K3C/K3C_5G 12345678/12345678
