### ISSUE TITLE
V2ray 问题

### ISSUE THREAD

**Issue by umud66** [paldier/K3C#6]
luci-app-v2ray的页面文件 是不是有些问题？

K3C/luci-app-v2ray/luasrc/model/cbi/v2ray.lua

`server = s:taboption("main",Value, "address", translate("Server Address"))`
`server:depends("use_conf_file", 1)`

`server_port = s:taboption("main",Value, "port", translate("Server Port"))`
`server_port:depends("use_conf_file", 0)`

server,server_port 这些配置文件的字段的depends应该是一致的吧

**Comment by umud66** [comment]
另外 depends("use_conf_file", 0) 的字段全部都不显示
不了解luci 所以没法去查找什么问题导致的
自用暂时改成了将use_conf_file 从 Flag 改成了ListValue

**Comment by paldier** [comment]
没有问题
