### ISSUE TITLE
PPPoE 不支持IPv6?

### ISSUE THREAD

**Issue by teslia** [paldier/K3C#8]
我没这边的ISP已经能支持IPv6，但是WAN设置PPPoE拨号后，无法取得IPv6地址。

**Comment by Nova41** [comment]
Same here.  I cannot get ipv6 addresses with WAN properly configured. (set PPPoE & enabled IPv6 negotiation)
While the ISDK firmware (another firmware made by paldier) has no problem getting an ipv6 prefix; DHCPv6 also works decently under ISDK firmware. I have no clue about this.

**Comment by paldier** [comment]
update to latest version

**Comment by Nova41** [comment]
> update to latest version

Amen, IPv6 still doesn't work. I've updated openwrt to the latest version and reset it to default. The IPv6 WAN status in the Network sections keeps displaying _Not connected._ Still not getting ipv6 addresses. :(

**My configuration:**
**WAN:** switched to PPPoE and enabled IPv6 negotiation & built-in management
**WAN6:** DHCPv6 (I didn't modify any part of it just kept it default)

**Comment by Nova41** [comment]
Sorry for not including logs in the previous comment.

System log: https://pastebin.com/raw/gaCmUZq8
Kernel log: https://pastebin.com/raw/US34dT3K
Oct 9 2018 - 1:53 PM

**Comment by paldier** [comment]
加群693673313测试一下新版本

**Comment by paldier** [comment]
已修复

**Comment by teslia** [comment]
感谢，已经确认！
